# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('genre', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to='images')),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('seasons', models.IntegerField(choices=[(1, 'Spring'), (2, 'Summer'), (3, 'Autumn'), (4, 'Winter')])),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClothesUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Clothes')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images')),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('defloration_date', models.DateField(blank=True)),
                ('expiration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LendEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=50)),
                ('lend_start', models.DateField()),
                ('lend_end', models.DateField()),
                ('books', models.ManyToManyField(to='home.Book')),
                ('clothes', models.ManyToManyField(to='home.Clothes')),
                ('meds', models.ManyToManyField(to='home.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('books', models.ManyToManyField(to='home.Book')),
                ('clothes', models.ManyToManyField(to='home.Clothes')),
                ('meds', models.ManyToManyField(to='home.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='TechAccessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images')),
                ('for_tech', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TechUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.TechAccessory')),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='tech',
            field=models.ManyToManyField(to='home.TechAccessory'),
        ),
        migrations.AddField(
            model_name='lendevent',
            name='tech',
            field=models.ManyToManyField(to='home.TechAccessory'),
        ),
    ]
